apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit-service
  template:
    metadata:
      labels:
        app: audit-service
    spec:
      containers:
        - name: audit-service
          image: gcr.io/reliable-mender-285316/audit
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          imagePullPolicy: Always